### ISSUE TITLE
ERROR: File easyelytrato_1.15-1.2.jar is not jar file

### ISSUE THREAD

**Issue by AlesonTalis** [Serilum/.issue-tracker#125]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.0
Environment: Singleplayer

Mod name: Easy Elytra Takeoff
Mod version: 1.2

## **Description**
"title"

## **Crash report**
[21mai2020 23:57:39.388] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, **********, --version, 1.15.2-forge-31.1.0, --gameDir, D:\MINECRAFT\FORGE\1.15.2-31.1.0, --assetsDir, C:\Users\aleso\AppData\Roaming\.minecraft\assets, --assetIndex, 1.15, --uuid, **********, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323]
[21mai2020 23:57:39.396] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_51 by Oracle Corporation
[21mai2020 23:57:39.497] [main/ERROR] [net.minecraftforge.fml.loading.ModDirTransformerDiscoverer/]: Zip Error when loading jar file D:\MINECRAFT\FORGE\1.15.2-31.1.0\mods\easyelytrato_1.15-1.2.jar
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:164) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:75) [forge-1.15.2-31.1.0.jar:31.1]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer$$Lambda$41/2036127838.accept(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_51]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:65) [forge-1.15.2-31.1.0.jar:31.1]
	at net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:37) [forge-1.15.2-31.1.0.jar:31.1]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$13(TransformationServicesHandler.java:137) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$37/116237769.apply(Unknown Source) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_51]
	at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:137) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:74) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
[21mai2020 23:57:39.990] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[21mai2020 23:57:40.880] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: File D:\MINECRAFT\FORGE\1.15.2-31.1.0\mods\easyelytrato_1.15-1.2.jar has been ignored - it is invalid
[21mai2020 23:57:41.882] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.15.2-forge-31.1.0, --gameDir, D:\MINECRAFT\FORGE\1.15.2-31.1.0, --assetsDir, C:\Users\aleso\AppData\Roaming\.minecraft\assets, --uuid, **********, --username, **********, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release]
[21mai2020 23:57:45.553] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: **********
[21mai2020 23:58:01.507] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[21mai2020 23:58:03.953] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.1.0, for MC 1.15.2 with MCP 20200122.131323
[21mai2020 23:58:03.954] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.1.0 Initialized
[21mai2020 23:58:08.362] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[21mai2020 23:58:08.439] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources, VanillaTweaks_r518793.zip
[21mai2020 23:58:15.071] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[21mai2020 23:58:15.894] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: OUTDATED Current: 31.1.0 Target: 31.2.0

**Comment by ricksouth** [comment]
Please re-download the file from CurseForge. That should solve the problem.

[https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff](https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff)
