### ISSUE TITLE
Tree Harvester is no longer compatible with dedicated servers

### ISSUE THREAD

**Issue by ejkarne** [Serilum/.issue-tracker#132]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.0
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 1.1

## **Description**
Tree Harvester is no longer compatible with dedicated servers. This is likely caused by the code targeting the sound engine which is not something being used by dedicated servers.

## **Crash report**
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 6/8/20, 6:33 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Tree Harvester (treeharvester) encountered an error during the complete event phase
§7Attempted to load class net/minecraft/client/audio/SoundEngine for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:271) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.end(ServerModLoader.java:56) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:181) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:832) [?:?] {}

**Comment by ricksouth** [comment]
Thanks for letting me know so quickly! The "client-only" annotation was hidden very well in the SoundEvent class. I've fixed it in version 1.2.

[https://www.curseforge.com/minecraft/mc-mods/tree-harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
