### ISSUE TITLE
Collective 1.36 - Exception generating new chunk

### ISSUE THREAD

**Issue by Mikeliro** [Serilum/.issue-tracker#226]
## **Information**
Minecraft version: 1.16.2
Forge version: 33.0.3
Environment: Singleplayer 

Mod name: Collective
Mod version: 1.36

## **Description**
Exception generating new chunk

## **Crash report**
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 14/08/20 14:43
Description: Exception generating new chunk

java.lang.ClassCastException: net.minecraft.world.gen.WorldGenRegion cannot be cast to net.minecraft.world.World
	at com.natamus.collective.events.MobSpawnEvents.onMobSpawn(MobSpawnEvents.java:30) ~[?:1.36] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_112_MobSpawnEvents_onMobSpawn_CheckSpawn.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:194) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1075) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:366) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:619) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2261/554530747.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5691/368999083.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5688/1938418229.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5617/2003536997.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.natamus.collective.events.MobSpawnEvents.onMobSpawn(MobSpawnEvents.java:30)
	at net.minecraftforge.eventbus.ASMEventHandler_112_MobSpawnEvents_onMobSpawn_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:194)
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1075)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:366)
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:619)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:89)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2261/554530747.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198)

-- Chunk to be generated --
Details:
	Location: -11,8
	Position hash: 38654705653
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@5f2b0d41
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524)
	at net.minecraft.world.server.ChunkManager$$Lambda$5691/368999083.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:522)
	at net.minecraft.world.server.ChunkManager$$Lambda$5688/1938418229.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5617/2003536997.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Mikeliro'/229, l='ServerLevel[Novo mundo]', x=-40.94, y=72.00, z=157.93]]
	Chunk stats: ServerChunkCache: 2061
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,90,128), Chunk: (at 0,5,0 in 1,8; contains blocks 16,0,128 to 31,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18923 game time, 18923 day time
	Level name: Novo mundo
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 109333 (now: false), thunder time: 139642 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)
	at net.minecraft.server.MinecraftServer$$Lambda$5477/957717268.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2882185616 bytes (2748 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.3.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.3.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.3
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.3-client.jar Minecraft {minecraft@1.16.2 DONE}
		PT - Useful Backpacks [1.11.3.76] [U Team].jar Useful Backpacks {usefulbackpacks@1.11.3.76 DONE}
		NO - Lenient Creepers [1.0.1].jar LenientCreepers {lenientcreepers@v1.0.1 DONE}
		NO - Zombie Proof Doors [1.0] [Collective].jar Zombie Proof Doors {zombieproofdoors@1.0 DONE}
		NO - Tree Harvester [1.3] [Collective].jar Tree Harvester {treeharvester@1.3 DONE}
		PT - Jei [7.1.0.11].jar Just Enough Items {jei@7.1.0.11 DONE}
		NO - Ceiling Torch [1.8].jar Ceiling Torch {ceilingtorch@v1.8 DONE}
		EN - Falling Tree [2.2.2].jar Falling Tree {falling_tree@2.2.2 DONE}
		PT - Easy Villagers[1.0.2].jar Easy Villagers {easy_villagers@1.16.2-1.0.2 DONE}
		NO - Reap [1.0.1].jar Reap Mod {reap@1.16.2-1.0.1 DONE}
		NO - Klee Slabs [9.1.0].jar KleeSlabs {kleeslabs@9.1.0 DONE}
		EN - [Core] Curios [4.0.0.0] #.jar Curios API {curios@1.16.2-4.0.0.0 DONE}
		NO - [Core] Collective [1.36].jar Collective {collective@1.36 DONE}
		NO - Softer Hay Bales [1.1] [Collective].jar Softer Hay Bales {softerhayb@1.1 DONE}
		NO - Overpowered Mending [2.2.2].jar Overpowered Mending {overpowered_mending@2.2.2 DONE}
		PT - Fake Blocks [1.0.2].jar Fake Blocks {fakeblocks@1.16.2-1.0.2 DONE}
		EN - Factory [1.1.1].jar Factory Mod {factory@1.16.2-1.1.1 DONE}
		NO - Curio Of Undying [5.0.0.0] [Curios].jar Curio of Undying {curioofundying@1.16.2-5.0.0.0 DONE}
		EN - Tubes Reloaded [1.4.0.1].jar Tubes Reloaded {tubesreloaded@1.16.2-1.4.0.1 DONE}
		EN - [Core] U Team [3.1.4.172].jar U Team Core {uteamcore@3.1.4.172 DONE}
		PT - Wormhole [1.0.7].jar Wormhole (Portals) {wormhole@1.0.7 DONE}
		NO - Shulker Drops Two [1.2] [Collective].jar Shulker Drops Two {shulkerdt@1.2 DONE}
		PT - Enchant With Mob [1.5.0].jar Enchant With Mob {enchantwithmob@1.16.2-1.5.0 DONE}
		NO - Inventory Essentials [2.1.0].jar Inventory Essentials {inventoryessentials@2.1.0 DONE}
		forge-1.16.2-33.0.3-universal.jar Forge {forge@33.0.3 DONE}
		EN - Travellers Map [0.5.4] #.jar Travellers Map {travellers_map@1.16.2-0.5.4 DONE}
		EN - Air Hop [1.3.1] #.jar Air Hop {airhop@1.3.1 DONE}
		PT - Corpse [1.0.3].jar Corpse {corpse@1.16.2-1.0.3 DONE}
		NO - Weaker Spiderwebs [1.4] [Collective].jar Weaker Spiderwebs {weakerspwbs@1.4 DONE}
		NO - Replanting Crops [1.4] [Collective ].jar Replanting Crops {replantingcrops@1.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Mikeliro'/229, l='ServerLevel[Novo mundo]', x=-40.94, y=72.00, z=157.93]]
	Data Packs: vanilla, mod:factory (incompatible), mod:lenientcreepers, mod:curioofundying, mod:tubesreloaded (incompatible), mod:wormhole (incompatible), mod:jei, mod:ceilingtorch, mod:falling_tree, mod:enchantwithmob, mod:forge (incompatible), mod:easy_villagers, mod:reap, mod:curios, mod:overpowered_mending, mod:airhop (incompatible), mod:corpse, mod:fakeblocks, mod:usefulbackpacks, mod:zombieproofdoors, mod:treeharvester, mod:kleeslabs (incompatible), mod:collective, mod:softerhayb, mod:uteamcore, mod:shulkerdt, mod:inventoryessentials (incompatible), mod:travellers_map (incompatible), mod:weakerspwbs, mod:replantingcrops
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by ricksouth** [comment]
This has been fixed in Collective version 1.37. Thanks for opening the issue!
