### ISSUE TITLE
Exception from malformed color code in areas signs kicks players when client tries to render overlay.

### ISSUE THREAD

**Issue by ramou** [Serilum/.issue-tracker#292]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.41
Environment: Multiplayer
Modpack: https://www.curseforge.com/minecraft/modpacks/imagine-no-dragons/files

Mod name: areas
Mod version: areas_1.15-1.0.jar

## **Description**
When creating a signpost I entered a line `[RGB] 90, 90, 90` instead of `[RGB] 90,90,90`. I was kicked and could not log back in till I hunted down the region file on the server, found the offending TileEntity in NBT Explorer and replaced the block. My guess is that it is using `split(",")` instead of `split(", ?")` or a more general match. More specifically, I'm guessing the more obvious issue is that it's not managing the NumberFormatException well.

## **Crash report**
````
java.lang.NumberFormatException: For input string: " 90"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_261] {}
	at com.natamus.areas.events.GUIEvent.renderOverlay(GUIEvent.java:61) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1694_GUIEvent_renderOverlay_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:831) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:660) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_175180_a(ForgeIngameGui.java:186) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:byg.mixins.json:client.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.41-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
````

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed it in version 1.1 of the mod, sorry for the inconvenience. Both your input should now be accepted and I've added an extra NumberFormatException catch.

[https://www.curseforge.com/minecraft/mc-mods/areas](https://www.curseforge.com/minecraft/mc-mods/areas)
