### ISSUE TITLE
Occassional ArrayIndexOutOfBoundsException on startup

### ISSUE THREAD

**Issue by ameisen** [Serilum/.issue-tracker#352]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.15
Environment: N/A

Mod name: Zombie Horse Spawn
Mod version: 2.5

## **Description**
Occasional crash on game startup before entering the menu.

I'd fix it myself, but the source does not appear to be available and I don't feel like decompiling the jar.

## **Crash report**
```
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?] {re:computing_frames}
-- MOD zombiehs --
Details:
	Mod File: zombiehs_1.16.4-2.5.jar
	Failure message: Zombie Horse Spawn (zombiehs) encountered an error during the complete event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	Mod Version: 2.5
	Mod Issue URL: https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Zombie%20Horse%20Spawn
	Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
Stacktrace:
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?] {re:computing_frames}
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?] {re:computing_frames}
	at com.natamus.collective.objects.SAMObject.<init>(SAMObject.java:30) ~[collective:1.53] {re:classloading}
	at com.natamus.zombiehorsespawn.Main.loadComplete(Main.java:36) ~[zombiehs:1.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
```

**Comment by ricksouth** [comment]
This has been fixed in version 1.58 of Collective. Thanks for submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/collective
