### ISSUE TITLE
Limited Bulk Download

### ISSUE THREAD

**Issue by dheivs** [Serilum/.issue-tracker#612]
## **Information**

Mod name: All Mods

## **Question**
I went to the bulk download page but it only shows 50 mods even I selected the "ALL" option. Before, I was able to download all 120+ of your updated mods. Were there only 50 updated mods for now because I was counting the mods that you uploaded in Curseforge and they are more than 100 mods for sure.

Just saying, I don't use all of your mods in one world. BUT, I use 30 of your mods to my world#1, then 50 to the other (and so on, I just love your work so much). Basically, I am using all of your mods but divided into different worlds.

I hope to get an answer. Thanks!!!

**Comment by James103** [comment]
Doing the above steps prints the following list of mods to the browser's console:
```
Error adding mod advancement-screenshot.
Error adding mod always-a-wither-skull.
Error adding mod automatic-doors.
Error adding mod bamboo-spreads.
Error adding mod bigger-sponge-absorption-radius.
Error adding mod breedable-killer-rabbit.
Error adding mod conduits-prevent-drowned.
Error adding mod configurable-mob-potion-effects.
Error adding mod creative-block-replacer.
Error adding mod crying-ghasts.
Error adding mod death-backup.
Error adding mod difficulty-lock.
Error adding mod enchanting-commands.
Error adding mod entity-information.
Error adding mod eroding-stone-entities.
Error adding mod extended-creative-inventory.
Error adding mod extract-poison.
Error adding mod fall-through-slime.
Error adding mod fire-spread-tweaks.
Error adding mod fish-on-the-line.
Error adding mod full-brightness-toggle.
Error adding mod giant-spawn.
Error adding mod grass-seeds.
Error adding mod grindstone-sharper-tools.
Error adding mod gui-followers.
Error adding mod healing-soup.
Error adding mod hide-hands.
Error adding mod humbling-bundle.
Error adding mod husk-spawn.
Error adding mod ice-prevents-crop-growth.
Error adding mod kelp-fertilizer.
Error adding mod milk-all-the-mobs.
Error adding mod mineral-chance.
Error adding mod mooshroom-spawn.
Error adding mod move-boats.
Error adding mod move-minecarts.
Error adding mod nutritious-milk.
Error adding mod omega-mute.
Error adding mod paper-books.
Error adding mod passive-endermen.
Error adding mod passive-shield.
Error adding mod pet-names.
Error adding mod placeable-blaze-rods.
Error adding mod player-death-kick.
Error adding mod player-tracking.
Error adding mod player-tracking-compass.
Error adding mod quick-paths.
Error adding mod rain-be-gone-ritual.
Error adding mod random-mob-effects.
Error adding mod random-sheep-colours.
Error adding mod random-shulker-colours.
Error adding mod realistic-bees.
Error adding mod recast.
Error adding mod recipe-commands.
Error adding mod replanting-crops.
Error adding mod respawn-delay.
Error adding mod respawning-shulkers.
Error adding mod save-and-load-inventories.
Error adding mod scaffolding-drops-nearby.
Error adding mod shulker-drops-two.
Error adding mod silence-mobs.
Error adding mod sleep-sooner.
Error adding mod softer-hay-bales.
Error adding mod spiders-produce-webs.
Error adding mod stack-refill.
Error adding mod stray-spawn.
Error adding mod superflat-world-no-slimes.
Error adding mod the-vanilla-experience.
Error adding mod tnt-breaks-bedrock.
Error adding mod trample-everything.
Error adding mod transcending-trident.
Error adding mod village-bell-recipe.
Error adding mod villager-death-messages.
Error adding mod vote-command.
Error adding mod wool-tweaks.
Error adding mod world-border.
Error adding mod zombie-proof-doors.
Error adding mod zombie-villagers-from-spawner.
```

I set a breakpoint to occur on the console.log statement that is executed (printing the strings above) when it fails to add a mod. Upon inspecting the variables, I get the following error:

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at addToCart (https://minecraft.natamus.com/assets/js/script.js:925:29)
    at HTMLButtonElement.<anonymous> (https://minecraft.natamus.com/assets/js/script.js:1097:2)
    at HTMLDivElement.dispatch (https://minecraft.natamus.com/assets/external/js/jquery-3.4.1.min.js:2:42571)
    at HTMLDivElement.v.handle (https://minecraft.natamus.com/assets/external/js/jquery-3.4.1.min.js:2:40572)
```

Additionally, hovering over the thumbnails for any of the above mods that error shows that the mods each show up as having only 1 download total and does not show a summary panel. Clicking through causes the website to hang (with the error shown above). Any modification of the filter by / search query also removes these mods from view.

**Comment by ricksouth** [comment]
Thanks @dheivs and @James103! I suppose Overwolf decided to limit their API access. Before it was possible to get the entire query in one go. Now it's limited to 50 entries. I've written a script which grabs all the individual data and put a file with all of it here on Github. The website now receives its information from this file instead of doing it via the API.

Everything should work again! :)
