### ISSUE TITLE
This thing just breaks in 1.17.1

### ISSUE THREAD

**Issue by ToshieCosed** [Serilum/.issue-tracker#655]
## **Information**
Minecraft version: 1.17.1 (Forge)
Forge version: 1.17.1-37.0.27
Environment: Server

Mod name: TreeHarvester
Mod version: treeharvester_1.17.1-2.7.jar

## **Description**
Mysterious Crash..

## **Crash report**
2021-08-07 21:03:09,798 main WARN Advanced terminal features are not available in this environment
[21:03:09] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 37.0.27, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038, nogui]
[21:03:09] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.2 by Oracle Corporation
[21:03:11] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.16/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:89)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at MC-BOOTSTRAP/fmlloader@1.17.1-37.0.27/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 7 more
Caused by: java.lang.IllegalAccessError: class net.minecraftforge.registries.GameData$ClearableObjectIntIdentityMap tried to access private field net.minecraft.core.IdMapper.f_122654_ (net.minecraftforge.registries.GameData$ClearableObjectIntIdentityMap is in module forge@37.0.27 of loader 'TRANSFORMER' @61861a29; net.minecraft.core.IdMapper is in module minecraft@1.17.1 of loader 'TRANSFORMER' @61861a29)
        at TRANSFORMER/forge@37.0.27/net.minecraftforge.registries.GameData$ClearableObjectIntIdentityMap.clear(GameData.java:418)
        at TRANSFORMER/forge@37.0.27/net.minecraftforge.registries.GameData$BlockCallbacks.onClear(GameData.java:471)
        at TRANSFORMER/forge@37.0.27/net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:539)
        at TRANSFORMER/forge@37.0.27/net.minecraftforge.registries.GameData.loadRegistry(GameData.java:695)
        at TRANSFORMER/forge@37.0.27/net.minecraftforge.registries.GameData.vanillaSnapshot(GameData.java:269)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:53)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.Main.main(Main.java:97)
        ... 13 more

**Comment by ricksouth** [comment]
Do you have the full crash report in ./crash-reports for me?
