### ISSUE TITLE
Game crashes when breaking log blocks with Shift pressed

### ISSUE THREAD

**Issue by DragosIvan** [Serilum/.issue-tracker#666]
## **Information**
Minecraft version: 1.17.1
Forge version: 37.0.33
Environment: Singleplayer

Mod name: Tree Harvester / Collective Library
Mod version: 2.9 / 2.57

## **Description**
The game crashes after I break a few log blocks with the Shift key pressed, or without it if "treeHarvestWithoutSneak" is set to "true", but with no axe in hand. I have a mod that adds a few new tools (EasySteel) and a few others (I attached the part of the crash report that shows the mods as well), but I don't think this is related to that, since it crashes in Creative when breaking log blocks while holding any random block. If it makes any difference, I'm also on Linux, but from what I can see in the stacktrace I don't think it should matter.

PS: Thank you for your work, it is greatly appreciated!

## **Crash report**

`---- Minecraft Crash Report ----

Time: 8/13/21, 1:46 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'java.util.Set net.minecraft.world.item.ItemStack.getToolTypes()'
	at com.natamus.collective.functions.ToolFunctions.isAxe(ToolFunctions.java:45) ~[collective-1.17.1-2.57.jar%2353!:2.57] {re:classloading}
	at com.natamus.treeharvester.events.TreeEvent.onTreeHarvest(TreeEvent.java:126) ~[treeharvester_1.17.1-2.9.jar%2357!:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_67_TreeEvent_onTreeHarvest_BreakEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:546) ~[forge-1.17.1-37.0.33-universal.jar%2363!:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:227) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:146) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:941) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(SourceFile:34) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(SourceFile:8) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(SourceFile:21) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(SourceFile:151) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(SourceFile:125) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(SourceFile:134) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:738) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.11.0-7620-generic
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 829390904 bytes (790 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 4800H with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: TU117M [GeForce GTX 1650 Ti Mobile]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1f95
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16048.27
	Virtual memory used (MB): 15675.51
	Swap memory total (MB): 4095.49
	Swap memory used (MB): 38.46
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 1 / 8; [ServerPlayer['Matthew__w'/476, l='ServerLevel[1.17.1 Modded]', x=-1510.34, y=97.00, z=498.80]]
	Data Packs: vanilla, mod:enhancedfarming, mod:forge (incompatible), mod:easy_steel, mod:biomesoplenty, mod:cfm, mod:collective, mod:xaerominimapfair (incompatible), mod:treeharvester
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		Enhanced-Farming-1.17.1-1.2.1.jar                 |Enhanced Farming              |enhancedfarming               |1.2.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.33-universal.jar                |Forge                         |forge                         |37.0.33             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		EasySteel-Forge-1.17.1-1.4.0.jar                  |Easy Steel & More             |easy_steel                    |1.4.0               |DONE      |Manifest: NOSIGNATURE
		Biomes-O-Plenty-Mod-1.17.1.jar                    |Biomes O' Plenty              |biomesoplenty                 |1.17.1-14.0.0.29    |DONE      |Manifest: NOSIGNATURE
		MrCrayfishs-Furniture-Mod-1.17.1.jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre24         |DONE      |Manifest: NOSIGNATURE
		collective-1.17.1-2.57.jar                        |Collective                    |collective                    |2.57                |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_FP21.14.1_Forge_1.17.1.jar         |Xaero's Minimap               |xaerominimapfair              |21.14.1             |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.17.1-2.9.jar                      |Tree Harvester                |treeharvester                 |2.9                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d97e62ed-763e-4eb1-be5d-c2833fa94495
	FML: 37.0
	Forge: net.minecraftforge:37.0.33`

**Comment by ricksouth** [comment]
Thanks for opening the bug report and giving the mod a try! This is due to the changes made in Forge version 37.0.31. I've just released Collective version 2.58 which will fix the issue you were having.

https://www.curseforge.com/minecraft/mc-mods/collective/files/all

**Comment by DragosIvan** [comment]
Thank you very much!

**Comment by DragosIvan** [comment]
Tested and confirmed the bug is fixed. Thank you again!

**Comment by ricksouth** [comment]
Great! Thanks for confirming.
