### ISSUE TITLE
Anvil Restoration Bug

### ISSUE THREAD

**Issue by mhallice** [Serilum/.issue-tracker#693]
Seems anvil Restoration messes with obsidian? With it installed Obsidian instantly breaks when you interact with it and gives the following error with the "does not exist in Block" part being whatever block the obsidian is placed on. If it is placed on another obsidian block it will say "minecraft:air"

Error executing task on Server
java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:grass_block}
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.world.level.block.state.StateHolder.m_61143_(SourceFile:98)
	at TRANSFORMER/anvilrestoration@1.0/com.natamus.anvilrestoration.events.AnvilInteractEvent.onAnvilClick(AnvilInteractEvent.java:40)
	at net.minecraftforge.eventbus.ASMEventHandler_150_AnvilInteractEvent_onAnvilClick_RightClickBlock.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@37.0.58/net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:753)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:315)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:971)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(SourceFile:30)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(SourceFile:8)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.protocol.PacketUtils.m_131356_(SourceFile:21)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.TickTask.run(SourceFile:18)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(SourceFile:151)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(SourceFile:125)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(SourceFile:134)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:738)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687)
	at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! I've fixed it in version 1.1.

https://www.curseforge.com/minecraft/mc-mods/anvil-restoration/files/all
