### ISSUE TITLE
CompareBlockFunctions Crash

### ISSUE THREAD

**Issue by reddvilzz** [Serilum/.issue-tracker#694]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Environment: Singleplayer

Mod name: Nether Portal Spread
Mod version: 5.4

## **Description**
Crash after igniting the nether portal with flint and steel, after that everytime I'm trying to return to overworld from nether will give me crash, going from overworld to nether it's fine though. Using MC Eternal.

## **Crash report**
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2021-09-12 01:44:30 ICT
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/natamus/collective/functions/CompareBlockFunctions
    at com.natamus.netherportalspread.util.Util.validatePortalAndAdd(Util.java:263)
    at com.natamus.netherportalspread.events.SpreadEvent.onWorldTick(SpreadEvent.java:41)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4692_SpreadEvent_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by James103** [comment]
Can you please attach the **full** crash report as a txt file, Github Gist, or paste.ee?

**Comment by reddvilzz** [comment]
[crash-2021-09-12_02.12.47-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/7148388/crash-2021-09-12_02.12.47-server.txt)

Here it is

**Comment by ricksouth** [comment]
Seems like you don't have the latest Collective version. What is the jar name inside your mods folder (e.g. collective-*) or the collective version inside the mod list?

**Comment by ricksouth** [comment]
Ah, from inside the crash log: collective-1.12.2-2.25.jar
Update Collective to the latest version, which should solve the problem. Did you update Nether Portal Spread yourself manually?

**Comment by reddvilzz** [comment]
Oh okay that fixed it thank you for the fast responses.

I don't recall updating, or is it part of the modpack.

Going to close the issue now, thank you so much.
